### PR TITLE
Overlap temp icon+fix cutoff

### PR DESCRIPTION
**Pull request by smitgd**
Since readability was not good on some KDE themes (e.g., breeze) I changed the panel icon (compact view) to font symbols. This uses a black/white simple style of weather font/icon that gives better contrast under various conditions. It uses the same method as github project plasma-applet-weather-widget and uses fonts from github project erikflowers/weather-icons. These fonts are not gpl3 but are based on another license that seems to be compatible so maybe the README.md will need to be updated if you decide to accept this change.

### CODE REVIEW

**Comment by librehat** [comment]
What is the license for this font file? We need to make sure it's GPL-compatible.
Another concern from me is whether it still has good contrast under different desktop themes (dark/light)

**Comment by smitgd** [comment]
Downloaded and tried several more light and dark themes and looked OK. However, with the debian default "breeze" theme there was a bit of problem seeing the temperature over the "wi-thunderstorm" icon. However, setting the font.weight to a darker value improved it greatly without affecting the other themes. 
I also noticed (again only on breeze theme) that the busy indicator in the panel was too large and overlapped some the adjacent panel item. Setting the busy indicator height and width to the parent keeps the busy indicator just over the weather icon/temperature.
I have push these changes to overlap-temp-icon+fix-cutoff branch (but now some conflicts on the P.R. that I haven't looked at yet since you did some other merges).

The font license info is here:
https://github.com/erikflowers/weather-icons/blob/master/README.md
Since we would only be using the font and not the code or documentation, the font file itself is covered by this license:
http://scripts.sil.org/OFL
This license does not supercede the current GPL license and seems compatible (I'm not a lawyer).  It should be mentioned in your README.md and say that it pertains only to the new font file. All other files still covered by GPL. I notice that the project that I used as a reference, and is distributed with debian and fedora and possibly other distros, does **not** mention the font license and only mentions GPL: https://github.com/kotelnik/plasma-applet-weather-widget .  Legally, I think they should also mention the font license (again, I am not a lawyer).

**Comment by librehat** [comment]
SIL OFL 1.1 is compatible with GPL. But we may need to update the README file to point this out.

I merged another pull request from you but I'm not sure why there is a conflict. It'll be great if you could sync and rebase to master to address conflicts.

**Comment by smitgd** [comment]
I compressed the PR into a new branch with no conflict. I will close this PR and make a new one with just one new commit (branch called font-style-panel-icons).
I also went ahead and updated the README.md with the license info for the font file and included it in the commit.

**Pull request closed without merging**
