### PR TITLE
Update zh_TW translation.

### PR DESCRIPTION
**Pull request by s8321414**
Please review and merge it :smiley:

### CODE REVIEW

**Comment by librehat** [comment]
General -> 一般？ Sure? Not 常规 or 通用？

**Comment by s8321414** [comment]
@librehat Sure, this zh_TW locales but not zh_CN...

**Comment by s8321414** [comment]
:+1:

**Comment by s8321414** [comment]
Could you please add
Name[zh_TW]=Yahoo 天氣小工具
and
Comment[zh_TW]=一個簡單的天氣監視器
to metadata.desktop?

**Comment by s8321414** [comment]
@librehat 
Could you please add
Name[zh_TW]=Yahoo 天氣小工具
and
Comment[zh_TW]=一個簡單的天氣監視器
to metadata.desktop?

**Comment by librehat** [comment]
I'll do it someday..

**Comment by s8321414** [comment]
:+1:

**Pull request merged**
