### PR TITLE
Wind direction backend

### PR DESCRIPTION
**Pull request by pejakm**
Added `parseWind` function which turns wind direction codes to labels with arrow.

So, for example, if the code is 350, it means wind is blowing from north, hence the label "⭣ N".

This doesn't add anything to ui yet.

### CODE REVIEW

**Comment by pejakm** [comment]
References #26.

**Comment by librehat** [comment]
Did you use some special characters? It doesn't display well in my browser or `Kate`.

Also, please squash your commits into one.

**Comment by librehat** [comment]
Simple unicode characters for now would be good enough ← → ↑ ↓ ↖ ↗ ↘ ↙
Also not really need to show the English abbr. such as "NE". The arrow is very intuitive.

**Comment by pejakm** [comment]
It displays fine here using Liberation Sans and Fira Sans fonts. I used arrows from "Mathematical symbols - Various symbols and arrows" utf-8 group. I intentionally avoided arrows you suggested because diagonal ones look slightly larger.

**Comment by pejakm** [comment]
I screwed something up when squashing so I can't push to this branch anymore. I'll just make another PR, sorry.

**Pull request closed without merging**
